config/routes.rb
Rails.application.routes.draw do
  resources :runners
  resources :races

  get 'photos/search', :to => 'photos#search'
  resources :photos

  devise_for :photographers
  resources :photographers
  get '/ping', to: 'health_check#health_check'
  mount Sidekiq::Web => '/sidekiq'

  root 'home#index'
end

app/models/race.rb
class Race < ApplicationRecord
  has_many :assignments, dependent: :destroy
  has_many :photographers, :through => :assignments
  has_many :photos, dependent: :destroy
  has_many :race_participations, dependent: :destroy
  has_many :runners, :through => :race_participations

  validates_presence_of :name, :start_date
  validates_numericality_of :distance, greater_than_or_equal_to: 0

  def name_with_year
    "#{name} #{start_date.year}"
  end

end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :set_race, only: [:show, :edit, :update, :destroy]

  # GET /races
  def index
    @races = Race.all
  end

  # GET /races/1
  def show
  end

  # GET /races/new
  def new
    @race = Race.new
  end

  # GET /races/1/edit
  def edit
  end

  # POST /races
  def create
    @race = Race.new(race_params)

    if @race.save
      redirect_to @race, notice: 'Race was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /races/1
  def update
    if @race.update(race_params)
      redirect_to @race, notice: 'Race was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /races/1
  def destroy
    @race.destroy
    redirect_to races_url, notice: 'Race was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race
      @race = Race.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def race_params
      params.require(:race).permit(:name, :start_date, :distance)
    end
end

app/helpers/race_helper.rb
module RaceHelper
  def official_race_photo_img(race)
    official_race_photo = race.photos.where(race_official: true).first
    return image_tag('', alt: 'Race Official Photo') if official_race_photo.nil?

    image_tag(official_race_photo.image.url, alt: 'Race Official Photo', height: '300', width: '300')
  end
end

app/views/races/_form.html.erb
<%= form_for @race do |f| %>

  <div class="form-group row">
    <label for="name" class="col-3 col-form-label">Race Name</label>
    <div class="col-4 input-group">
      <%= f.text_field :name, id: 'name', class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <label for="race_date" class="col-3 col-form-label">Race Date</label>
    <div class="col-4 input-group">
      <%= f.date_field :start_date, id: 'start_date', class: 'form-control' %>
    </div>
  </div>

  <div class="form-group row">
    <label for="distance" class="col-3 col-form-label">Distance</label>
    <div class="col-4 input-group">
      <%= f.text_field :distance, id: 'distance', type: 'float', min: 0, class: 'form-control' %>
      <span class="input-group-prepend input-group-addon">KM</span>
    </div>
  </div>

  <div class="text-center">
    <%= f.submit class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/races/edit.html.erb
<h1>Editing Race</h1>

<%= render 'form', race: @race %>

<%= link_to 'Show', @race %> |
<%= link_to 'Back', races_path %>

app/views/races/index.html.erb
<% content_for :page_title, "Races" %>

<div class="container">

  <div class="row mb-5">
    <%= button_to 'New Race', new_race_path, class: "btn btn-primary", method: :get %>
  </div>

  <div class="row">
    <% @races.each do |race| %>

      <div class="col-sm-6 col-xl-4 mb-5">
        <div class="card h-100 border-0 shadow">
          <%= link_to race do %>
            <div style="background-image: url(<%= race.photos.where(race_official: true).first.image.url %>); min-height: 300px;" class="card-img-top overflow-hidden bg-cover">
              <div class="card-img-overlay-top d-flex justify-content-between align-items-center">
                <div class="badge badge-transparent badge-pill px-3 py-2">Race</div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/races/new.html.erb
<% content_for :page_title, 'New Race' %>

<div class="row">
  <div class="col-sm-12">
    <%= render 'shared/errors', resource: @race %>

    <%= render 'form', race: @race %>
  </div>
</div>

app/views/races/show.html.erb
<% content_for :page_title, "Race" %>

<div><%= @race.name %> </div>
<div><%= @race.distance %> KM</div>
<div><%= @race.start_date %> </div>

<div class="container-fluid">
  <div class="col-12" style="text-align: center">
    <% @race.photos.each do |photo| %>
      <%= link_to photo do %>
        <%= image_tag photo.image.url, class: "col-3" %>
      <% end %>
    <% end %>
  </div>
</div>
<%= link_to 'Edit', edit_race_path(@race) %>
<%= link_to 'Back', races_path %>