config/routes.rb
Rails.application.routes.draw do
  resources :runners
  resources :races

  get 'photos/search', :to => 'photos#search'
  resources :photos

  devise_for :photographers
  resources :photographers
  get '/ping', to: 'health_check#health_check'
  mount Sidekiq::Web => '/sidekiq'

  root 'home#index'
end

app/models/runner.rb
class Runner < ApplicationRecord
  has_many :race_participations
  has_many :races, through: :race_participations
  has_and_belongs_to_many :photos
end

app/controllers/runners_controller.rb
class RunnersController < ApplicationController
  before_action :set_runner, only: [:show, :edit, :update, :destroy]

  # GET /runners
  def index
    @runners = Runner.all
  end

  # GET /runners/1
  def show
  end

  # GET /runners/new
  def new
    @runner = Runner.new
  end

  # GET /runners/1/edit
  def edit
  end

  # POST /runners
  def create
    @runner = Runner.new(runner_params)

    if @runner.save
      redirect_to @runner, notice: 'Runner was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /runners/1
  def update
    if @runner.update(runner_params)
      redirect_to @runner, notice: 'Runner was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /runners/1
  def destroy
    @runner.destroy
    redirect_to runners_url, notice: 'Runner was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_runner
      @runner = Runner.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def runner_params
      params.fetch(:runner, {})
    end
end

app/views/runners/_form.html.erb
<%= form_with(model: runner, local: true) do |form| %>
  <% if runner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(runner.errors.count, "error") %> prohibited this runner from being saved:</h2>

      <ul>
      <% runner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/runners/edit.html.erb
<h1>Editing Runner</h1>

<%= render 'form', runner: @runner %>

<%= link_to 'Show', @runner %> |
<%= link_to 'Back', runners_path %>

app/views/runners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Runners</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @runners.each do |runner| %>
      <tr>
        <td><%= link_to 'Show', runner %></td>
        <td><%= link_to 'Edit', edit_runner_path(runner) %></td>
        <td><%= link_to 'Destroy', runner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Runner', new_runner_path %>

app/views/runners/new.html.erb
<h1>New Runner</h1>

<%= render 'form', runner: @runner %>

<%= link_to 'Back', runners_path %>

app/views/runners/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_runner_path(@runner) %> |
<%= link_to 'Back', runners_path %>