config/routes.rb
Rails.application.routes.draw do
  resources :runners
  resources :races

  get 'photos/search', :to => 'photos#search'
  resources :photos

  devise_for :photographers
  resources :photographers
  get '/ping', to: 'health_check#health_check'
  mount Sidekiq::Web => '/sidekiq'

  root 'home#index'
end

app/views/layouts/_topbar.html.erb
<nav class="navbar navbar-expand-lg fixed-top shadow navbar-light bg-white">
  <div class="container-fluid">
    <div class="d-flex align-items-center">
      <%= link_to image_tag('logo.svg'), '/', class:"navbar-brand py-1"  %>
    </div>
    <button type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler navbar-toggler-right">
      <i class="fa fa-bars"></i></button>
    <div id="navbarCollapse" class="collapse navbar-collapse">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to "Races", races_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Photos", photos_path, class: 'nav-link' %>
        </li>
        <li class="nav-item mt-3 mt-lg-0 ml-lg-3 d-lg-none d-xl-inline-block">
          <%= link_to 'Add a photo', new_photo_path, class: 'btn btn-primary' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eleven</title>
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= controller_javascript_include_tag %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,400i,700">

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/solid.css" integrity="sha384-TbilV5Lbhlwdyc4RuIV/JhD8NR+BfMrvz4BL5QFa2we1hQu6wvREr3v6XSRfCTRp" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/regular.css" integrity="sha384-avJt9MoJH2rB4PKRsJRHZv7yiFZn8LrnXuzvmZoD3fh1aL6aM6s0BBcnCvBe6XSD" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/brands.css" integrity="sha384-7xAnn7Zm3QC1jFjVc1A6v/toepoG3JXboQYzbM0jrPzou9OFXm/fY6Z/XiIebl/k" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/fontawesome.css" integrity="sha384-ozJwkrqb90Oa3ZNb+yKFW2lToAWYdTiF1vt8JiH5ptTGHTGcN7qdoR1F95e0kYyG" crossorigin="anonymous">

</head>
<body style="padding-top: 72px;">
<%= render 'layouts/topbar' %>

<div class="content">

  <% if content_for?(:page_title) %>
    <div class="row border-bottom mb-4">
      <div class="col-12">
        <h1 class="display-4 font-weight-bold text-serif mb-4 ml-6"><%= yield(:page_title) %></h1>
      </div>
    </div>
  <% end %>

  <div id="error-container">
    <%= render partial: "shared/messages" %>
  </div>

  <%= yield %>

</div>

</body>
</html>